name: Docker Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Test Docker Compose
      run: |
        docker-compose config -q
        docker-compose pull
        docker-compose up -d
        sleep 30
        docker-compose ps
        docker-compose down 